[package]
name = "host"
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
clap = { workspace = true }
common = { path = "../common" }
crossterm = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
plotters = { default-features = false, features = ["bitmap_backend", "bitmap_encoder", "image", "line_series", "ttf"], version = "0.3.7" }
ratatui = { workspace = true }
serialport = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
usb-tmc = { path = "../usb-tmc" }
