// Generates `src/generated/` from the characteriser's results schema: a copy of
// the schema, which the page validates results files against, and TypeScript
// types for it.
//
// Run with `pnpm generate` after the schema changes. CI fails if the committed
// output is out of date.

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { compile, type JSONSchema } from 'json-schema-to-typescript';

const SCHEMA = new URL('../characteriser/schemas/characterisation.schema.json', import.meta.url);
const OUTPUT = new URL('./src/generated/', import.meta.url);

const text = await readFile(SCHEMA, 'utf8');

const schema = withoutReferenceDescriptions(JSON.parse(text)) as JSONSchema;
const types = await compile(schema, 'Characterisation', {
  bannerComment:
    '// Generated by `pnpm generate` from the characteriser\'s\n' +
    '// schemas/characterisation.schema.json. Don\'t edit by hand.',

  // Only the types that deny unknown fields say so in the schema, but a results
  // file never has fields its types don't, so none needs an index signature.
  additionalProperties: false,
});

await mkdir(OUTPUT, { recursive: true });
await writeFile(new URL('characterisation.schema.json', OUTPUT), text);
await writeFile(new URL('characterisation.ts', OUTPUT), types);

/**
 * `schema` with every `$ref`'s sibling keys removed.
 *
 * schemars gives a field that refers to a shared type, e.g. a `Derived`, the
 * field's own description beside the `$ref`. json-schema-to-typescript then
 * generates a separate copy of the type for each such field (`Derived1`,
 * `Derived2`, …) instead of referring to the one. Without the descriptions,
 * every field refers to the same type. The field descriptions are lost from
 * the generated types, but the shared types keep their own.
 */
function withoutReferenceDescriptions(schema: unknown): unknown {
  if (Array.isArray(schema)) {
    return schema.map(withoutReferenceDescriptions);
  }
  if (typeof schema !== 'object' || schema === null) {
    return schema;
  }
  if ('$ref' in schema) {
    return { $ref: schema.$ref };
  }
  return Object.fromEntries(
    Object.entries(schema).map(([key, value]) => [key, withoutReferenceDescriptions(value)]),
  );
}
